allow building with gcc 10+
OnionIoT/source pull request #24
Opened 2021-01-15 16:00 UTC by Wint3rmute

Hey,

when building with Arch/Manjaro, the `prereq-build.mk` script misdetects `gcc 10.X.X` as too old (due to [5-9] range in the regex). I patched the regexes checking the compiler version so that it is possible to build with `gcc 10+` without overriding all the prerequisites checks.

2021-07-16 14:36 UTC, greenbreakfast commented
@Wint3rmute sorry for the delayed response. Were you able to resolve the issue?

2022-09-12 06:49 UTC, huntc commented
My work-around is to install v9 having installed build-essentials per the doc:

```
sudo apt install gcc-9 g++-9
```

...then make it known:

```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
```

...then:

```
sudo update-alternatives --config gcc
```

Inspiration: https://linuxize.com/post/how-to-install-gcc-on-ubuntu-20-04/#installing-multiple-gcc-versions

2022-09-13 00:47 UTC, EyitopeIO commented
But build-essentials gets a compatible gcc. So what exactly is causing to build to fail ?

2022-09-18 13:16 UTC, ggirelli commented
I believe the build is failing because the regexp used for the check supports only versions from 4.8 up to `9.y.z`:
```
Build dependency: Please install the GNU C Compiler (gcc) 4.8 or later cc -dumpversion | grep -E '^(4\.[8-9]|[5-9]\.?)'
Build dependency: Please install the GNU C++ Compiler (g++) 4.8 or later g++ -dumpversion | grep -E '^(4\.[8-9]|[5-9]\.?)'
```

2022-09-18 13:24 UTC, ggirelli requested changes

2022-09-18 13:24 UTC, ggirelli commented on include/prereq-build.mk
> +	g++ -dumpversion | grep -E '^(4\.[8-9]|[5-9]|10\.?)', \
Why not something like this instead?
```g++ -dumpversion | grep -E '^(4\.[8-9]|[5-9]\.?|1[0-9]\.?)', \```
This way compatibility for point versions from 5.y to 9.y is retained, while adding support for 10, 11,... up to 19.y.
This should be done also for gcc.

2022-12-15 09:19 UTC, closed without merging